### ISSUE TITLE
Indexing question for 17792rar241?

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/etda_workflow#475]
Hi, I had a catalog-related question for why the person was able to find https://etda.libraries.psu.edu/catalog/17792rar241 with a search for: `keyword: acoustics vibration` and year limited to 2021 in ETDA but no in the Catalog. I don't see "vibration" anywhere in the record's metadata.

Would it be possible to share the full Solr record for this item? (I see the word "vibration" a couple times in the PDF itself... do you index those or)

Is it simply that only one of two keyword fields must match? I noticed the Solr config mm is:

```
2&lt;-1 5&lt;-2 6&lt;90%<
```

**Comment by jrpatterson** [comment]
@AndrewGearhart   Can you look into this and let Ruth know?

**Comment by ruthtillman** [comment]
after opening I retried the search with a boolean and only got the same 5 results as the catalog. Is this possibly a case where the minimum match is so low that for 2 keywords it's returning either and that

```
3&lt;-1 5&lt;-2 6&lt;90%<
```

might make more sense?

**Comment by AndrewGearhart** [comment]
> after opening I retried the search with a boolean and only got the same 5 results as the catalog. Is this possibly a case where the minimum match is so low that for 2 keywords it's returning either and that
> 
> ```
> 3&lt;-1 5&lt;-2 6&lt;90%<
> ```
> 
> might make more sense?

Yes, precisely. :)
