### ISSUE TITLE
confupdate ArgumentError

### ISSUE THREAD

**Issue by whereismyjetpack** [psu-libraries/etda_workflow#521]
When running the graduate confhold rake task, the `confidential_hold_update_service` throws the following 

```
ArgumentError: wrong number of arguments (given 3, expected 2)
/etda_workflow/app/services/confidential_hold_update_service.rb:6:in `initialize'
```

what's peculiar, is this only appears to be happening for the graduate school, I think this is because in k8s, honors for example returns nil with `Author.all`

**Comment by ajkiessl** [comment]
fixed by #524
