### ISSUE TITLE
Verify Files task

### ISSUE THREAD

**Issue by ajkiessl** [psu-libraries/etda_workflow#522]
We are not going to run this with our initial release.  We are not sure this needs to be run.  It does a search for a file, to check that it is generally in the right place.  Not sure what intent was for this?  It may have been useful after a migration to check that all of the files moved to the right place.  This could be simplified to just loop over final submission files and check the file exists with an exact path.

**Comment by whereismyjetpack** [comment]
CarrierWave location: irb(main):007:0> FinalSubmissionFile.last.asset.file.file
