### ISSUE TITLE
Confidential hold update cron

### ISSUE THREAD

**Issue by ajkiessl** [psu-libraries/etda_workflow#597]
Run the confidential hold update task regularly with cron again.  It seems that users will get their submission to "Waiting for publication release" with a confidential hold and then it will be removed.  At this point the users don't really log in anymore, so just updating confidential hold on login will not work here.  The question is, do we want to run this daily or weekly?  Confidential holds change very infrequently, so running it every day seems like overkill.  We also don't want to be sending too many requests to LDAP.

**Comment by jrpatterson** [comment]
I think weekly seems good.  If we need to, we can manually have it run.
________________________________
From: Alex Kiessling ***@***.***>
Sent: Monday, December 12, 2022 5:32 PM
To: psu-libraries/etda_workflow ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [psu-libraries/etda_workflow] Confidential hold update cron (Issue #597)


Run the confidential hold update task regularly with cron again. It seems that users will get their submission to "Waiting for publication release" with a confidential hold and then it will be removed. At this point the users don't really log in anymore, so just updating confidential hold on login will not work here. The question is, do we want to run this daily or weekly? Confidential holds change very infrequently, so running it every day seems like overkill. We also don't want to be sending too many requests to LDAP.
