### ISSUE TITLE
Schreyer Reports

### ISSUE THREAD

**Issue by jrpatterson** [psu-libraries/etda_workflow#638]
Good morning- In the reports we can generate from EHT, there is a field for Advisor Name but no field for Thesis Supervisor.  Could you add that as a field that's reported in the CSV file? That would let us skip the very cumbersome step of cross-referencing our internal (and sometimes dated) records when we make the graduation program.

Thanks-
Richard Stoller

**Comment by jrpatterson** [comment]
Would it be easier to list out all the committee members with their role in the report?

**Comment by ajkiessl** [comment]
I think that might be too much.
