### ISSUE TITLE
Investigate removing `#committee_rejected_admin` mailer

### ISSUE THREAD

**Issue by ajkiessl** [psu-libraries/etda_workflow#731]
Graduate admins say this is not needed.  Also, it sends an email to the admin mail list, which is not typical.  The system usually sends emails directly to the graduate school (the partner) email.  Consider removing this mailer entirely.  We should investigate to make sure this wasn't something essential to one of the other partners first, though.

**Comment by ajkiessl** [comment]
![Screenshot 2024-04-02 at 1 51 57 PM](https://github.com/psu-libraries/etda_workflow/assets/32677188/10bf13a3-2d90-4894-bd5d-bcf496cc59f4)

This can actually be toggled on/off in the approval configuration screen.  Maybe we should just add some help text here.

**Comment by binkylush** [comment]
Spoke with Fawn Hosterman and we can just add the help text to the configuration screen. No other change needed.
