### ISSUE TITLE
Communications and automation for the release of Restricted theses/dissertations

### ISSUE THREAD

**Issue by ajkiessl** [psu-libraries/etda_workflow#757]
From Grad School:

> When a student's 2 years are up, we would like ETD to notify the student a month ahead of time via their email PSU and alternate email , letting them know they can either add another 1 year or to release to open access. When the communication is sent to the student, we would like ETD to automatically update the release date if they do ask for an extension.  No further extensions to be granted.

We could make this work by generating a unique link and sending that with the email to the student.  If the student clicks that link, it will send a request back to ETDA with that link, triggering the extension in the system.

**Comment by ajkiessl** [comment]
> Dear, 

> We are writing to inform you that your two-year restriction is about to expire. Please indicate below if you would like to extend your restriction or release your work to open access. If we do not hear from you, your work will automatically be released to open access. 

>Thank You,
>Office of Theses and Dissertations

Somewhere in this email will need to be a link to trigger the extension.

**Comment by ajkiessl** [comment]
It appears the Grad School would also like to automate the release of restricted submissions.  Right now admins must manually select the theses/dissertations they'd like to release.  We'd need some kind of cron task to do this.

**Comment by binkylush** [comment]
Per Rich Stoller, Shreyer's Honors College is on board with this update as well.
