### ISSUE TITLE
ETD Semester Hold

### ISSUE THREAD

**Issue by ajkiessl** [psu-libraries/etda_workflow#758]
From Grad School:

> Make it so that only students who are graduating in the current graduation semester and one semester in advance can upload format reviews and final submissions (e.g. during Summer 2024, only students with graduation semester Summer 2024 and Fall 2024 can upload format reviews and final submissions; everyone else is given a notice that says "Graduation period has not yet started, please upload when the semester you are graduating has begun. Contact your program or OTD if you have questions"

> Right now, these are sitting in the mix with the current graduating students.

**Comment by ajkiessl** [comment]
I think the main problem here is that students will upload something very early, and leave it there.  Then, when their graduation semester comes around and it's time to finish it, they inevitably want to restart it because something is wrong.

**Comment by ajkiessl** [comment]
We could solve this for the Grad School by not importing submission from LionPATH until the semester before graduation.

**Comment by binkylush** [comment]
From Fawn - To simplify ETD Semester Hold, could the first submission drop down semester selection be only current semester + one semester.  I can explain my concerns with LP if needed and maybe I need to understand not importing from LP.  For the 2nd question, yes automating the release after the appropriate time period is fine.

**Comment by binkylush** [comment]
Per Rich Stoller, Shreyer's Honors College is on board with this update as well.

**Comment by Smullz622** [comment]
Wording from Fawn: Only upload your dissertation or thesis if you intend to graduate this semester or the following semester.
