### ISSUE TITLE
Update language related to federal funding

### ISSUE THREAD

**Issue by binkylush** [psu-libraries/etda_workflow#759]
Awaiting info from the Grad School

**Comment by binkylush** [comment]
May be a bit more complicated than just language.  Saty tuned!

**Comment by binkylush** [comment]
New language and workflow described in the attached doc...

[2024 05 EDTa Federal Funding Statement Update vs 1.1 OSP Approved FINAL(1).docx](https://github.com/user-attachments/files/15568323/2024.05.EDTa.Federal.Funding.Statement.Update.vs.1.1.OSP.Approved.FINAL.1.docx)

**Comment by binkylush** [comment]
Fawn and Jahmal will get us more information about what happens/where students should be directed/what emails they will receive if they answer "no" to any of the federal funding questions.

**Comment by ajkiessl** [comment]
The Grad School would like to meet with someone to get the wording for this, so whoever takes this issue should schedule a meeting with them.
