### ISSUE TITLE
ETD Submission Acknowledgment Format Review

### ISSUE THREAD

**Issue by ajkiessl** [psu-libraries/etda_workflow#760]
From the Grad School:

> When a student logs in to the ETD for the first time, we need students to go through a series of acknowledgment pages where they must type their initials in order to proceed. Have students acknowledge: 

> 1) I have read the thesis/dissertation handbook and understand how to format my thesis/dissertation to align with Graduate School Policy,  
> 2) I will reference the Graduate School's Thesis/Dissertaiton Template
> 3) I will ensure that the faculty titles of my committee members are listed correctly on the committee page of my thesis/dissertation 
> 4) I consulted with my advisor and we both have agreed that I did/did not utilize federal funding 
> 5) I know if it is the Program Head or Director of Graduate Studies of my program who needs to approve my thesis/dissertation. If I am not sure, I will consult with my program, 
> 6) I acknowledge that I cannot fix typos or make additional corrections after I submit my final submission 
> 7) I acknowledge that I cannot make committee changes after the final is submitted.

**Comment by ajkiessl** [comment]
I think you could just have all this on one page and still have the user initial for each one.  We discussed storing the results of this in the db.  If the Grad School has some use for this, then we can do that.  However, I think just requiring all the forms to have an initial before proceeding should be enough to remind the student to do these things.

**Comment by ajkiessl** [comment]
This will be a Grad School only thing.  Let's direct students to this when the first click on the "Update Program Information" button.  Once it's complete, they should not be directed back to this page.

**Comment by jlandiseigsti** [comment]
Do we only want a student to see this page once, even if they have multiple submissions?

**Comment by binkylush** [comment]
Grad school will get a us a title for this page.
