### ISSUE TITLE
Add Mailcatcher

### ISSUE THREAD

**Issue by ajkiessl** [psu-libraries/etda_workflow#761]
> OTD needs to see what the user sees. For this purpose, it would be helpful to have a dummy student account.

Using the QA instance should be sufficient for admins to see what authors see in the UI.  I think the biggest issue with QA was that it doesn't send out emails, which the admins would like to see.  

Come up with a way for admins to see the emails.  Mailcatcher?

**Comment by ajkiessl** [comment]
Let's implement Mailcatcher so admins can see emails there in QA.  We'll need to give them access to Mailcatcher and direct them to it.

**Comment by Smullz622** [comment]
Closed by https://github.com/psu-libraries/etda-config/pull/99 and https://github.com/psu-libraries/etda-config/pull/98
