### ISSUE TITLE
2/3 Vote Block

### ISSUE THREAD

**Issue by ajkiessl** [psu-libraries/etda_workflow#762]
From Grad School:

> The ETD system currently allows students' work to move from "final pending" to "final submitted" with only  2/3 approved vote. This results in work not being reviewed by the entire committee. We would like to put a stop to this, so that only students who have received votes from every one of their committee members move on to "final submission is submitted". This way, if a member doesn't vote, an OTD staff person could simply log that the committee member "did not vote" which would move the student's work to "final submission is submitted". We would also like a new communication to be sent where if ETD identifies that if 2/3 of the committee has approved, ETD will automatically email any committee member who has not voted. 

email:

Dear Professor,

We are writing to inform you that 2/3 of the committee has voted on this student’s final work. Unfortunately, a vote has not been entered for you at this time. We ask that you enter a vote within 7 days so that your name will appear in the student’s final work. If you do not respond within the 7-day period, your name will not appear in the student’s final work. 

Thank You,

Office of Theses and Dissertations

**Comment by ajkiessl** [comment]
We will have to change the seventh day evaluation worker to not update the submission status and change what emails go out to dissertation committees.  Right now, an email will go out to the committee chair and author for dissertations.  Do we still want this to happen?  Or should we just send emails out to committee members that need to vote?

**Comment by binkylush** [comment]
To clarify - 7 days after the email above goes out, the work should move to final submitted.

**Comment by ajkiessl** [comment]
Do we need another notification after the second 7 days?  Or just automatically update to "Did Not Vote"?

**Comment by Smullz622** [comment]
Got clarification from Fawn- we do not need to notify OTD; they are already monitoring. They would like us to still automatically update to "Did Not Vote" though

**Comment by Smullz622** [comment]
Update on preferred wording from Fawn:

Dear Dr. <last name>,              
This will be your final opportunity to vote on <student name>'s final work. If you do not vote within seven days, your name will be removed from the student’s work.
Add link to vote
 Thank You,
Office of Theses and Dissertations
