### ISSUE TITLE
Sending corrections to students through ETD

### ISSUE THREAD

**Issue by ajkiessl** [psu-libraries/etda_workflow#763]
From Grad School:

> As of now, OTD emails students their corrections in PDF, which is very manual and takes a lot of time. We would like ETD to allow us to send students our corrections through ETD so that everything is in one place.

We will need to add a field for admins to upload this document in the admin submission screen.  They can add any additional comments in the existing "Notes to Student" field.  Then, we we'll need a place for the student to download the file on the author end.

**Comment by binkylush** [comment]
Grad school will get us language for this. We will do a separate area for corrections (separate from format review).

**Comment by jlandiseigsti** [comment]
While we are making changes to these pages, Graduate School asked if we could set default text for the Admin Notes field for both Format Review and Final Submission.

Format Review: "The documents below contain your format review corrections, information on supporting materials, and the graduation checklist. Please refer to the Thesis and Dissertation Handbook when making corrections.

	The next step is to submit your final dissertation. The final dissertation must be reviewed and approved by all committee members and all changes made before it is uploaded to the eTD site for electronic approval. Formatting changes requested by the Office of Theses and Dissertations will be the only changes permitted after the final is uploaded."

Final Submission:
Your final submission requires further revisions. To see these revisions, open the PDF below in Adobe Acrobat. Please note this DOES NOT require you to get committee approvals again. Rather, make the requested revisions and then upload the corrected file to the ETDA. The Office of Theses and Dissertations will review your submission again until it is error-free. Please resubmit by the deadline for your intended graduation semester requirements. Not doing so puts you at risk of being removed from the graduation list.
Thank you and do reach out if you have any questions!
